volumes:
  mysqldata: {}
  azurite_data: {}


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18
        NPM_VERSION: 9
        NESTJS_VERSION: 10
        NG_VERSION: 17
        NX_VERSION: 17

    image: cleareye-dockershell
    hostname: cleareye-dockershell
    working_dir: /app
    depends_on:
      - db
      - phpmyadmin
    volumes:
      - ./:/app
      - ~/.npmrc:/root/.npmrc
      - ~/.npmrc:/home/node/.npmrc
      - ~/.npm/:/home/node/.npm
    ports:
      - '13000-13011:13000-13011'
    environment:
      APP_PORT_BACKEND: 13001

      # DB config
      APP_DB_HOST: db
      APP_DB_USER: app
      APP_DB_PASS: app
      APP_DB_NAME: app

    extra_hosts:
      - "host.docker.internal:host-gateway"

    logging:
      options:
        max-size: 10m
  db:
    image: mariadb:10.6
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD: root

